# Generated by Django 2.0 on 2018-01-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fds_content', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('fds_from', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. Почта')),
                ('fds_status', models.BooleanField(default=False)),
                ('fds_create_time', models.DateTimeField(auto_now_add=True)),
                ('fds_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
